[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
day1 = "adventofcode._2023._1.p1:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
